/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.server)
    api(libs.org.springframework.cloud.spring.cloud.starter.config)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

group = "com.airlines"
version = "0.0.1-SNAPSHOT"
description = "eureka-server-discovery"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
