/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "airlines-backend-microservices"

pluginManagement {
    val springBootVersion: String by settings
    val springDependencyManagementVersion: String by settings
    val kotlinVersion: String by settings
    val gradleGitVersion: String by settings
    val gradleDockerVersion: String by settings
    val swaggerGeneratorVersion: String by settings
    val openApiGeneratorPluginVersion: String by settings
    plugins {
        id("org.springframework.boot") version springBootVersion
        id("io.spring.dependency-management") version springDependencyManagementVersion
        kotlin("jvm") version kotlinVersion
        id("org.jetbrains.kotlin.plugin.spring") version kotlinVersion
        id("org.jetbrains.kotlin.plugin.jpa") version kotlinVersion
        id("org.jetbrains.kotlin.plugin.allopen") version kotlinVersion
        id("com.gorylenko.gradle-git-properties") version gradleGitVersion
        id("org.hidetake.swagger.generator") version swaggerGeneratorVersion
        id("com.bmuschko.docker-spring-boot-application") version gradleDockerVersion
        id("com.bmuschko.docker-remote-api") version gradleDockerVersion
        id("org.openapi.generator") version openApiGeneratorPluginVersion
    }
}

//libs
include(
    "flight",
    "mail-sender",
    "ticket",
    "ticket-pdf-generator",
    "tourist",
)
