apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlines-keycloak
  namespace: airlines-backend-microservices
  labels:
    app: airlines-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airlines-keycloak
  template:
    metadata:
      labels:
        app: airlines-keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: [ "start-dev" ]  # Required for Keycloak 17+
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres:5432/keycloak"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              value: "keycloakpassword"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
