/*
 * This file was generated by the Gradle 'init' task.
 * Adjusted to fit the multi‑project (root) build configuration.
 */

plugins {
    id("org.springframework.boot")
    id("io.spring.dependency-management")
    id("com.bmuschko.docker-spring-boot-application")
    kotlin("jvm")
}

dependencies {
    // Spring Boot Starters
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-amqp")

    // Spring Cloud Starters (versions managed via the BOM from the root)
    implementation("org.springframework.cloud:spring-cloud-starter-config")
    implementation("org.springframework.cloud:spring-cloud-starter-openfeign")

    // Swagger / API Documentation
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui")

    // Additional Test Dependencies
    testImplementation("org.springframework.amqp:spring-rabbit-test")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.bootJar {
    launchScript()
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

docker {
    val registryUrl = "default-route-openshift-image-registry.apps-crc.testing"
    val registryProject = "airlines-backend-microservices"
    val moduleName = project.name

    springBootApplication {
        baseImage.set("amazoncorretto:21")
        jvmArgs.set(listOf("-Duser.name=developer"))

        var images = setOf(
            "${registryUrl}/$registryProject/airlines-$moduleName:${version}",
        )
        if (version == "develop-SNAPSHOT") {
            images = images.plus("${registryUrl}/$registryProject/airlines-$moduleName:latest")
        }
        this.images.set(
            images,
        )
    }
}


description = "tourist"
