apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlines-tourist
  namespace: airlines-backend-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airlines-tourist
  template:
    metadata:
      labels:
        app: airlines-tourist
    spec:
      containers:
        - name: airlines-tourist
          image: default-route-openshift-image-registry.apps-crc.testing/airlines-backend-microservices/airlines-tourist:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airlines-tourist-config
            - secretRef:
                name: airlines-tourist-secrets
