apiVersion: v1
kind: Service
metadata:
  name: airlines-postgres-service
  namespace: airlines-backend-microservices
spec:
  selector:
    app: airlines-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
