server:
  port: 8080

spring:
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:airlines-mongodb-service}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:airlines}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}

  kafka:
    # Use env var KAFKA_BOOTSTRAP_SERVERS; default to in-cluster service name if not set
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:airlines-kafka-service:9092}

    consumer:
      group-id: myapp-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
