apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlines-mail-sender
  namespace: airlines-backend-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airlines-mail-sender
  template:
    metadata:
      labels:
        app: airlines-mail-sender
    spec:
      containers:
        - name: airlines-mail-sender
          image: default-route-openshift-image-registry.apps-crc.testing/airlines-backend-microservices/airlines-mail-sender:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airlines-mail-sender-config
            - secretRef:
                name: airlines-mail-sender-secrets
          env:
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_ROOT_USER
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_ROOT_PASSWORD
