apiVersion: v1
kind: Service
metadata:
  name: airlines-logstash-service
  namespace: airlines-backend-microservices
  labels:
    app: airlines-logstash
spec:
  selector:
    app: airlines-logstash
  ports:
    - name: beats
      protocol: TCP
      port: 5044
      targetPort: 5044
    - name: http
      protocol: TCP
      port: 9600
      targetPort: 9600
