/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.thymeleaf)
    api(libs.org.springframework.cloud.spring.cloud.starter.config)
    api(libs.ognl.ognl)
    api(libs.com.itextpdf.itextpdf)
    api(libs.com.itextpdf.html2pdf)
    api(libs.com.itextpdf.kernel)
    api(libs.com.itextpdf.tool.xmlworker)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.amqp)
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    api(libs.org.springframework.cloud.spring.cloud.starter.openfeign)
    api(libs.io.springfox.springfox.boot.starter)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.amqp.spring.rabbit.test)
    testImplementation(libs.org.springdoc.springdoc.openapi.webmvc.core)
}

group = "com.airlinesmicroservices"
version = "0.0.1-SNAPSHOT"
description = "ticket-pdf-generator"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
