apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlines-ticket
  namespace: airlines-backend-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airlines-ticket
  template:
    metadata:
      labels:
        app: airlines-ticket
    spec:
      containers:
        - name: airlines-ticket
          image: default-route-openshift-image-registry.apps-crc.testing/airlines-backend-microservices/airlines-ticket:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airlines-ticket-config
            - secretRef:
                name: airlines-ticket-secrets
