apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: airlines-ticket-route
  namespace: airlines-backend-microservices
spec:
  to:
    kind: Service
    name: airlines-ticket-service
  port:
    targetPort: 80
  tls:
    termination: edge
