apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: airlines-kafka
  namespace: airlines-backend-microservices
spec:
  # ----- Kafka brokers -----
  kafka:
    version: 3.4.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      # single-node settings
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: persistent-claim
      size: 5Gi
      class: standard
      deleteClaim: false

  # ----- ZooKeeper ensemble -----
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      class: standard
      deleteClaim: false

  # ----- Optional: auto-create topics & users -----
  entityOperator:
    topicOperator: {}
    userOperator: {}