name: Auto-number issues with [BE-<NUMBER>] prefix

# Trigger this workflow whenever a new issue is opened
on:
  issues:
    types: [opened]

# Grant write permission to issues so we can update the issue title
permissions:
  issues: write

jobs:
  auto_number_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq for JSON processing
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Capture new issue information
        id: new_issue
        run: |
          # OWNER and REPO for later gh api calls
          echo "OWNER=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
          echo "REPO=${{ github.repository_name }}" >> $GITHUB_OUTPUT
          # GitHub-assigned issue number (e.g. 27)
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          # Raw title entered by the user before we add [BE-<N>]
          echo "RAW_TITLE<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Determine current max BE- number among all issues
        id: find_max_be
        run: |
          OWNER="${{ steps.new_issue.outputs.OWNER }}"
