apiVersion: v1
kind: Service
metadata:
  name: airlines-mongodb-service
  namespace: airlines-backend-microservices
spec:
  clusterIP: None                     # headless service for StatefulSet DNS
  ports:
    - name: airlines-mongodb
      port: 27017
      targetPort: 27017
  selector:
    app: airlines-mongodb                      # picks up the StatefulSet Pods
